### ISSUE TITLE
Moegi 2 - Prototype

### ISSUE THREAD

**Issue by ddiu8081** [moegi-design/ghost-theme-Moegi#15]
The New Moegi is on the way! You can comment on this issue to share your idea. Hope we can make Moegi better.

----

Moegi 是我在博客主题领域的第一个尝试。尽管我致力于让 Moegi 更优雅，但它还不够完美。比如，对于颜色、字号没有统一规范，编写样式全靠眼缘；引入了很多第三方库，较为臃肿；首页的排列方式一直不尽人意......

于是，我决定更新一个 2.0 版本，把之前遗留的 todo list 继续完善，同时致力于解决这些问题。

目前，关于 2.0 我有这些打算。

* 面向设计稿开发
* 国际化与本地化
* 减少或取消对 jQuery 的依赖，采用 Vue 等一些更新的框架。
* 首页图片支持、站点 Logo 支持
* 针对页内超链接优化

如今，Moegi 2.0 的设计稿正在绘制中。你可以点击下面的原型设计稿查看最新进展。在下方评论你的想法，可以帮助我做得更好。

[Figma Prototype](https://www.figma.com/file/bV4Vrw6Ik3bFkFRunmzk7ss5/ghost-theme-Moegi-2?node-id=0%3A1)

[Moegi2 开发分支](https://github.com/moegi-design/ghost-theme-Moegi/tree/next)

**Comment by xiaolilir** [comment]
看了下设计稿，个人觉得文章的预览是否可以加个开关，让它显示呢？！

**Comment by ddiu8081** [comment]
> 看了下设计稿，个人觉得文章的预览是否可以加个开关，让它显示呢？！

会的，计划提供 pure/normal/card 三种展示形式

**Comment by Smith-Cruise** [comment]
加个数学公式显示功能吧

**Comment by ddiu8081** [comment]
> 加个数学公式显示功能吧

好的

**Comment by onedaydayde** [comment]
这种简洁的样式太漂亮很适合做笔记记录，代码高亮的行号显示可以进行自定义吗？就是显示和不显示的开关，另外，ghost3.0都发布了，新版的主题是否支持，还有多久能发布呢？

**Comment by ddiu8081** [comment]
> 这种简洁的样式太漂亮很适合做笔记记录，代码高亮的行号显示可以进行自定义吗？就是显示和不显示的开关，另外，ghost3.0都发布了，新版的主题是否支持，还有多久能发布呢？

@onedaydayde  Hi, Moegi 2已经切换为主分支并开始继续更新～感谢支持
