### ISSUE TITLE
Features Todo List

### ISSUE THREAD

**Issue by ddiu8081** [moegi-design/ghost-theme-Moegi#2]
> 主分支已切换为Moegi 2，旧有功能会初步迁移。
- [ ] 标签云
- [ ] 归档页
- [ ] 文章目录
- [ ] 评论功能
- [ ] 搜索功能
- [ ] 文章底部作者信息
- [x] 主题色更改
- [ ] 顶部进度条
- [ ] 图片灯箱
- [ ] 文章底部打赏功能
- [x] 顶部图片
- [x] 博客logo支持
- [x] 黑暗模式

**Comment by huayuanp** [comment]
纯粹来点赞的！可以放个二维码什么的,请作者喝几瓶可乐。😁

**Comment by ddiu8081** [comment]
@huayuanp 谢谢支持！
捐助的话..感觉还不够完善暂时不想这么做😂

等足够完善了我会考虑在博客里集成一个入口
再次感谢对项目的关注🙂

**Comment by novolei** [comment]
很喜欢作者这个主题 这个是迄今以来我见过最优雅的主题
只是套用了作者的TOC到我自己的主题上 显示不是很好 我不是做前端的
希望作者可以指点一下
http://bt-v.com/2018/08/14/zhong-wen-wang-ye-zhong-she-yu-pai-ban-typo-css/

**Comment by ddiu8081** [comment]
@novolei 看起来是hover和正常状态的padding不一致导致他会跳..
你给#toc a加一个padding:0就好多了😁
![](http://ostfcwjy3.bkt.clouddn.com/18-8-16/59575340.jpg)

**Comment by novolei** [comment]
thanks a lot, let me come back to trial it

**Comment by novolei** [comment]
果然是哦 加过之后就没有问题了 我怎么让hover上去的时候字变成你那个绿色呢？

**Comment by novolei** [comment]
我试着改a:hover下的颜色设置 好像不起作用

**Comment by novolei** [comment]
还有关于目录的字体大小我也找不到地方修改呢

**Comment by colynxu** [comment]
过来点个赞，这个主题几乎满足了我对于主题的所有期待。

**Comment by ddiu8081** [comment]
@colynxu 谢谢支持！

**Comment by haodong** [comment]
嗨~感谢作者的分享，我很喜欢这套主题。
这里还有一个不成熟的小建议：
这个主题很简洁，归档页是如此的简单，以至于完全不需要翻页~赞美！👍
我有一个更“激进”的想法，能否用归档页替代主页呢？毕竟，如果文章的标题足够给力的话，那么excerpt是多么多余啊！
如果「硬改」，归档页的标题“归档”二字还是会残留。所以，能否请作者添加这么一项“开关”——自定义首页用传统页面或者归档页面？
如果作者嫌不够技术含量，也可以考虑添加响应式、自动载入、甚至自动消失的功能，就像[这样](https://github.com/luokangyuan/ghost-theme-mj)。当然，这一条只是附加题，optional~😀

**Comment by ddiu8081** [comment]
@haodong 是的，我现在也是这么想的，打算做到下一个版上，或者带到2.0里
