### ISSUE TITLE
我做了一些修改，请指点。

### ISSUE THREAD

**Issue by ghost** [moegi-design/ghost-theme-Moegi#27]
https://e.ymjt.com.cn

1、增加 推荐文章加标记
2、修改 标签附上主色调
3、增加 时间改为 xx 以前（中文）
4、修改 搜索方法
5、修改 标签页以 tagcanvas 方式显示
6、增加 每个页面（除作者）标题图标
7、增加 文章页面阅读时间（中文）
8、修改 底部 footer_text 以支持 html
9、修改 公共 css、js CDN 为 bootcss.com

正在尝试在文章页面增加 赞/踩 功能（这个独立支持）

**Comment by ddiu8081** [comment]
很喜欢的改进，感谢支持！
如果希望将改动合入主题，可以提交pr😄

**Comment by e14883362** [comment]
> 很喜欢的改进，感谢支持！
> 如果希望将改动合入主题，可以提交pr😄

看一下 https://e.ymjt.com.cn/ghost-datetime/ 文章结尾部分。
我加了个前端：
`<script>
$(function(){ 
  
  getdata("/rating/do.php",'{{id}}'); 
   
  $("#dig_up").click(function(){ 
    getdata("/rating/do.php?action=like",'{{id}}'); 
  }); 

  $("#dig_down").click(function(){ 
    getdata("/rating/do.php?action=unlike",'{{id}}'); 
  }); 
});
  
function getdata(url,sid){ 
  $.getJSON(url,{id:sid},function(data){ 
    if(data.success==1){ 
      $("#num_up").html(data.like); 
      $("#num_down").html(data.unlike); 
    }
  }); 
} 
</script> `

后端一个数据查询、更新简单代码操作数据库。

**Comment by ddiu8081** [comment]
> > 很喜欢的改进，感谢支持！
> > 如果希望将改动合入主题，可以提交pr😄
> 
> 看一下 https://e.ymjt.com.cn/ghost-datetime/ 文章结尾部分。
> 我加了个前端，后端加一个数据查询、更新简单代码操作数据库。
> 
> 根据IP限制提交次数。

感觉可以像 Gitment/Gitalk 一样，把数据存在对应 issue 上🤨

**Comment by e14883362** [comment]
> > > 很喜欢的改进，感谢支持！
> > > 如果希望将改动合入主题，可以提交pr😄
> > 
> > 
> > 看一下 https://e.ymjt.com.cn/ghost-datetime/ 文章结尾部分。
> > 我加了个前端，后端加一个数据查询、更新简单代码操作数据库。
> > 根据IP限制提交次数。
> 
> 感觉可以像 Gitment/Gitalk 一样，把数据存在对应 issue 上🤨

我也这么想过，准备测试一下。但水平有限，试试吧。
