### ISSUE TITLE
没有开启评论功能，但是内页导航中出现了“评论”

### ISSUE THREAD

**Issue by dantewang** [moegi-design/ghost-theme-Moegi#29]
配置：`var show_valine = false;`

效果截图：
![moegi](https://user-images.githubusercontent.com/1185063/63218973-7e52f100-c19a-11e9-93eb-76bdf5624956.png)

看了一下，虽然关闭了评论功能，但页面代码中仍有评论相关的元素，只是用JS设置成了隐藏的（参见comment.hbs）。

**Comment by ddiu8081** [comment]
js隐藏确实从观感和逻辑上都不太好，后续会把模块加载方式改成真·不渲染
