### ISSUE TITLE
现在Ghost更新版本了，有3.0.3版本，主题有没有考虑做适配。

### ISSUE THREAD

**Issue by wzyxdwll** [moegi-design/ghost-theme-Moegi#33]
现在Ghost更新版本了，有3.0.3版本，现在的主题对新版的Ghost 有一些API和样式不支持，作者是否考虑对其做支持？

**Comment by ddiu8081** [comment]
@wzyxdwll  欢迎回来！基于 Ghost 3.x 的适配主题 Moegi 2开发正在进行中，可以访问 [Demo](https://notes.ddiu.site/) 。
