### ISSUE TITLE
Meogi  2.0 主页跳转 bug

### ISSUE THREAD

**Issue by yuxiaoba** [moegi-design/ghost-theme-Moegi#37]
看到作者 2.0 版本 release ，赶紧尝试了一下。

我在 ghost 3.0 版本上尝试了一下最新的 Meogi 2.0 ，发现了主页跳转可能有个小 bug

我的主页是  https://blog.yuxiaoba.xyz/ 

在主页的目录里，点击某个已发布的 post， 页面跳转为 http://localhost:2368/the-editor/

它不能自动跳转为 https://blog.yuxiaoba.xyz/the-editor/

**Comment by ddiu8081** [comment]
感谢关注。应该是命令行安装ghost的过程中指定了url为` http://localhost:2368/`所致。
可以进入ghost目录检查一下配置是否正确：`ghost setup`

**Comment by yuxiaoba** [comment]
ok, 已经搞定了
