### ISSUE TITLE
How can I apply syntax highlighter such as highlighter.js on this theme?

### ISSUE THREAD

**Issue by dev4ndr3w** [moegi-design/ghost-theme-Moegi#39]

**Comment by dev4ndr3w** [comment]
Sorry for late reply :(
I have still issue to syntax highlighting
![Screenshot_20200704-202315_Brave](https://user-images.githubusercontent.com/40394063/86511452-590fb580-be34-11ea-8a4a-92254cfa7a18.jpg)
Have you any solution for this?

**Comment by ddiu8081** [comment]
@dev4ndr3w 
The default languages PriamJS supports are `markup`, `css`, `clike` and `javascript`, 
so `c` might not supported yet, you can use `clike` instead.
And I will add an configuration to support more languages soon. Thanks for your advice

**Comment by dev4ndr3w** [comment]
I love your theme among ever other themes. because it's so minimal design and cool 😍 
I really hope various languages support feature release as soon as possible!
Keep it up! 👍 👍

**Comment by ddiu8081** [comment]
Hi @dev4ndr3w ,
Thanks to the [Autoloader plugin](https://prismjs.com/plugins/autoloader/), all language in https://prismjs.com/#supported-languages has been supported.
No need to declare manually, languages will be automatically imported as needed.
commit in 506d28e6e57941a82eb778727d6d30dae72d8411 and 13f377a07afb97ac2954df6ebe2f95a044e70137
